# Generated by Django 2.1.5 on 2019-01-24 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('issue', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('year_in_school', models.CharField(choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], default=2019, max_length=4)),
                ('publication_sort', models.CharField(choices=[('Books&Magazines', 'Books&Magazines'), ('Patent', 'Patent'), ('International Conference', 'International Conference'), ('Domestic Conference', 'Domestic Conference')], default='International Conference', max_length=20)),
            ],
        ),
    ]
