# Generated by Django 2.1.5 on 2019-02-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='blog',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='award',
            field=models.TextField(null=True),
        ),
    ]
