# Generated by Django 2.1.7 on 2019-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190210_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='blog',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='publication',
            name='award',
            field=models.TextField(blank=True),
        ),
    ]
